import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  weight:['300','400','500'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Riffly",
  description: "Generated by create next app",
  icons:{
    icon: "images/RifflyLogo.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body
        className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
